#!/bin/bash

threshold=20

used=$(df -h / | grep '/' | awk '{print $5}' | tr -d '%')

if [ "$used" -ge $((100 - threshold)) ]; then
  echo "Low disk space: $used% used"
else
  echo "Disk usage is okay: $used% used"
fi
